default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DB_HOST") %>
  port: <%= ENV.fetch("DB_PORT") %>
  username: <%= ENV.fetch("DB_USERNAME") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

production:
  <<: *default
  database: <%= "#{ENV.fetch("APP_NAME")}_#{ENV.fetch("APP_ENV")}"%>

development:
  <<: *default
  database: <%= "#{ENV.fetch("APP_NAME")}_#{ENV.fetch("APP_ENV")}"%>

test:
  <<: *default
  database: <%= "#{ENV.fetch("APP_NAME")}_#{ENV.fetch("APP_ENV")}"%>