default: &default
  adapter: postgresql
  encoding: unicode
  host: 0.0.0.0
  port: 5431
  username: main
  password: main
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= "#{ENV.fetch("APP_NAME")}_#{ENV.fetch("APP_ENV")}"%>

test:
  <<: *default
  database: <%= "#{ENV.fetch("APP_NAME")}_#{ENV.fetch("APP_ENV")}"%>